"""Phase 2 xG-map migration: native A/B plots + clustering checks.

This script consumes a Phase 1 coverage report generated by
`python -m BlackhawksSkillEstimation.compare_xg_coverage` and:

1) Produces native-resolution Cartesian heatmaps for sampled event_ids:
   - Overlap IDs: side-by-side (legacy vs new)
   - New-only / legacy-only IDs: single panel for the available source

2) Produces clustering CSVs (set-based SQL using EXISTS/NOT EXISTS):
   - Per-season top games by new_only_count and legacy_only_count
   - Per-season top players by new_only_count and legacy_only_count

Usage
-----
python -m BlackhawksSkillEstimation.plot_xg_map_migration_samples
python -m BlackhawksSkillEstimation.plot_xg_map_migration_samples --max-events 25
python -m BlackhawksSkillEstimation.plot_xg_map_migration_samples --report-json Data/Hockey/migration_reports/xg_coverage_YYYYMMDD_HHMMSS_report.json
"""

from __future__ import annotations

import argparse
import json
import random
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from BlackhawksAPI import db
from BlackhawksAPI import queries
from BlackhawksSkillEstimation.blackhawks_plots import plot_xg_map_cartesian_native

LEGACY_TABLE = "hawks_analytics.post_shot_xg_value_maps"
NEW_TABLE = "hawks_analytics.expected_goal_values_post_shot_net_grid"

DEFAULT_REPORT_DIR = Path("Data/Hockey/migration_reports")
DEFAULT_PLOTS_ROOT = Path("Data/Hockey/plots/xg_map_migration")


def _normalize_shot_type(token: str) -> str:
    """Normalize a shot-type token for case/spacing differences.

    Example: "Wrist Shot" -> "wristshot", "snap-shot" -> "snapshot".
    """

    return "".join(ch for ch in (token or "").strip().lower() if ch.isalnum())


@dataclass(frozen=True)
class SampleEvent:
    event_id: int
    season: int | None
    sample_bucket: str


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Phase 2 xG-map migration: native A/B sanity plots + clustering CSVs."
    )
    p.add_argument(
        "--report-json",
        type=Path,
        default=None,
        help=(
            "Path to a Phase 1 JSON report. If omitted, uses the latest "
            "xg_coverage_*_report.json under Data/Hockey/migration_reports."
        ),
    )
    p.add_argument(
        "--max-events",
        type=int,
        default=25,
        help="Max number of events to plot (default: 25).",
    )
    p.add_argument(
        "--from-plot-dir",
        type=Path,
        default=None,
        help=(
            "Optional existing plot directory to re-render. If provided, the script parses event IDs "
            "from filenames (season_*_event_*_*.png) and ignores the Phase 1 report and filters."
        ),
    )
    p.add_argument(
        "--seasons",
        type=int,
        nargs="+",
        default=None,
        help=(
            "Seasons to sample from when using filtered sampling (default: 20232024 20242025). "
            "Ignored when sampling directly from a Phase 1 report (unless you also pass filters)."
        ),
    )
    p.add_argument(
        "--player-ids-file",
        type=Path,
        default=None,
        help=(
            "Optional file containing PLAYER_ID_HAWKS values (one per line). "
            "When provided, the script samples events directly via SQL using this filter."
        ),
    )
    p.add_argument(
        "--shot-types",
        type=str,
        nargs="+",
        default=None,
        help=(
            "Optional shot types to include (case/spacing-insensitive). Example: --shot-types wristshot snapshot. "
            "When provided, filters PUBLIC.EVENT.SHOT_TYPE accordingly."
        ),
    )
    p.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed used for filtered SQL sampling (default: 0).",
    )
    p.add_argument(
        "--plots-root",
        type=Path,
        default=DEFAULT_PLOTS_ROOT,
        help="Root output directory for plots (default: Data/Hockey/plots/xg_map_migration).",
    )
    p.add_argument(
        "--out-report-dir",
        type=Path,
        default=DEFAULT_REPORT_DIR,
        help="Directory to write clustering CSVs (default: Data/Hockey/migration_reports).",
    )
    p.add_argument(
        "--top-n",
        type=int,
        default=25,
        help="Top-N per season to keep in clustering CSVs (default: 25).",
    )
    p.add_argument(
        "--skip-plots",
        action="store_true",
        help="Skip plot generation (clustering only).",
    )
    p.add_argument(
        "--skip-clustering",
        action="store_true",
        help="Skip clustering CSVs (plots only).",
    )
    return p


def _find_latest_report(report_dir: Path) -> Path:
    candidates = list(report_dir.glob("xg_coverage_*_report.json"))
    if not candidates:
        raise FileNotFoundError(
            f"No Phase 1 reports found under {report_dir}. Expected files like xg_coverage_*_report.json"
        )
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _load_phase1_report(path: Path) -> dict:
    payload = json.loads(path.read_text())
    if not isinstance(payload, dict):
        raise ValueError(f"Report JSON must be an object; got {type(payload)}")
    if "samples" not in payload:
        raise ValueError("Report JSON missing 'samples' key")
    return payload


def _iter_sample_events(payload: dict) -> list[SampleEvent]:
    samples = payload.get("samples") or {}
    out: list[SampleEvent] = []

    def add_bucket(bucket: str) -> None:
        for season_str, season_samples in samples.items():
            try:
                season = int(season_str)
            except Exception:  # noqa: BLE001
                season = None

            if not isinstance(season_samples, dict):
                continue

            for eid in season_samples.get(bucket, []) or []:
                if eid is None:
                    continue
                out.append(
                    SampleEvent(
                        event_id=int(eid),
                        season=season,
                        sample_bucket=bucket,
                    )
                )

    # Preferred order: overlap first (for side-by-side), then mismatches.
    add_bucket("overlap")
    add_bucket("legacy_only")
    add_bucket("new_only")

    # De-dupe while preserving order.
    seen: set[int] = set()
    deduped: list[SampleEvent] = []
    for s in out:
        if s.event_id in seen:
            continue
        seen.add(s.event_id)
        deduped.append(s)

    return deduped


def _load_player_ids(path: Path) -> list[int]:
    """Load integer player IDs from a text file (one per line).

    Ignores blank lines and comment lines beginning with '#'.
    """

    raw = path.read_text(encoding="utf-8").splitlines()
    out: list[int] = []
    for line in raw:
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        try:
            out.append(int(s))
        except ValueError:
            continue
    # de-dupe while preserving order
    seen: set[int] = set()
    uniq: list[int] = []
    for pid in out:
        if pid in seen:
            continue
        seen.add(pid)
        uniq.append(pid)
    return uniq


def _sql_in_ints(values: list[int]) -> str:
    return ",".join(str(int(v)) for v in values)


def _sql_shot_type_clause(shot_types: list[str] | None) -> str:
    if not shot_types:
        return ""
    normalized = sorted({_normalize_shot_type(x) for x in shot_types if x is not None})
    normalized = [x for x in normalized if x]
    if not normalized:
        return ""

    # Normalize PUBLIC.EVENT.SHOT_TYPE by removing non-alphanumerics and lowercasing.
    # This matches tokens like "Wrist Shot" / "wristshot" / "wrist-shot".
    allowed_sql = ",".join(f"'{x}'" for x in normalized)
    return (
        "AND REGEXP_REPLACE(LOWER(COALESCE(e.SHOT_TYPE, '')), '[^a-z0-9]', '') "
        f"IN ({allowed_sql})"
    )


def _sql_player_clause(player_ids: list[int] | None) -> str:
    if not player_ids:
        return ""
    return f"AND e.PLAYER_ID_HAWKS IN ({_sql_in_ints(player_ids)})"


def _sample_overlap_events_filtered(
    *,
    seasons: list[int],
    player_ids: list[int] | None,
    shot_types: list[str] | None,
    max_events: int,
    seed: int,
) -> list[SampleEvent]:
    """Sample overlap event_ids directly from Snowflake with optional filters."""

    seasons_str = _sql_in_ints(seasons)
    player_clause = _sql_player_clause(player_ids)
    shot_clause = _sql_shot_type_clause(shot_types)

    # Pull a reasonable pool, then sample client-side to avoid relying on DB RNG.
    # If the filtered pool is small, we will just use what exists.
    pool_limit = max(500, int(max_events) * 30)

    query = f"""
        SELECT DISTINCT
            e.EVENT_ID_HAWKS AS event_id_hawks,
            g.SEASON         AS season
        FROM public.event AS e
        JOIN public.game  AS g
          ON g.GAME_ID_HAWKS = e.GAME_ID_HAWKS
        WHERE g.SEASON IN ({seasons_str})
          AND e.EVENT_NAME = 'shot'
          {player_clause}
          {shot_clause}
          AND EXISTS (SELECT 1 FROM {LEGACY_TABLE} l WHERE l.EVENT_ID_HAWKS = e.EVENT_ID_HAWKS)
          AND EXISTS (SELECT 1 FROM {NEW_TABLE}    n WHERE n.EVENT_ID_HAWKS = e.EVENT_ID_HAWKS)
        LIMIT {int(pool_limit)}
        ;
    """

    df = db.get_df(query).rename(columns=str.lower)
    if df.empty:
        return []

    pool = [
        SampleEvent(event_id=int(r["event_id_hawks"]), season=int(r["season"]), sample_bucket="overlap")
        for r in df.to_dict(orient="records")
        if r.get("event_id_hawks") is not None
    ]

    rng = random.Random(int(seed))
    if len(pool) <= max_events:
        return pool

    # Sample without replacement.
    picked = rng.sample(pool, k=int(max_events))
    return picked


def _safe_min_max(x: np.ndarray) -> tuple[float | None, float | None]:
    arr = np.asarray(x, dtype=float)
    if arr.size == 0:
        return None, None
    vmin = float(np.nanmin(arr))
    vmax = float(np.nanmax(arr))
    if not np.isfinite(vmin) or not np.isfinite(vmax):
        return None, None
    if vmax <= vmin:
        vmax = vmin + 1e-9
    return vmin, vmax


def _safe_mean(x: np.ndarray) -> float:
    arr = np.asarray(x, dtype=float)
    if arr.size == 0:
        return 0.0
    m = float(np.nanmean(arr))
    if not np.isfinite(m):
        return 0.0
    return m


def _annotate_avg_xg(ax: plt.Axes, avg_xg: float) -> None:
    ax.text(
        0.02,
        0.98,
        f"avg xG: {avg_xg:.4f}",
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=8,
        color="#222222",
        bbox=dict(boxstyle="round,pad=0.2", facecolor="#ffffff", edgecolor="none", alpha=0.75),
    )


def _safe_max(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    if x.size == 0:
        return 0.0
    m = float(np.nanmax(x))
    if not np.isfinite(m):
        return 0.0
    return m


def _parse_plot_dir_events(plot_dir: Path) -> list[SampleEvent]:
    if not plot_dir.exists():
        raise FileNotFoundError(f"Plot dir not found: {plot_dir}")

    pattern = re.compile(r"^(?:season_(\d+)_)?event_(\d+)_([a-z_]+)\.png$")
    events: list[SampleEvent] = []

    for path in sorted(plot_dir.glob("*.png")):
        m = pattern.match(path.name)
        if not m:
            continue
        season_str, event_str, source_tag = m.groups()
        season = int(season_str) if season_str else None
        event_id = int(event_str)

        bucket = "overlap"
        if source_tag:
            has_legacy = "legacy" in source_tag
            has_new = "new" in source_tag
            if has_legacy and not has_new:
                bucket = "legacy_only"
            elif has_new and not has_legacy:
                bucket = "new_only"

        events.append(SampleEvent(event_id=event_id, season=season, sample_bucket=bucket))

    # De-dupe while preserving order.
    seen: set[int] = set()
    deduped: list[SampleEvent] = []
    for s in events:
        if s.event_id in seen:
            continue
        seen.add(s.event_id)
        deduped.append(s)
    return deduped


def _plot_event(
    *,
    event_id: int,
    season: int | None,
    legacy: dict[str, object] | None,
    new: dict[str, object] | None,
    out_dir: Path,
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    legacy_map = None if legacy is None else legacy.get("value_map")
    legacy_coords = None if legacy is None else legacy.get("net_coords")

    new_map = None if new is None else new.get("value_map")
    new_coords = None if new is None else new.get("net_coords")

    sources: list[str] = []
    if legacy_map is not None:
        sources.append("legacy")
    if new_map is not None:
        sources.append("new")
    if not sources:
        raise ValueError(f"Event {event_id}: neither legacy nor new map present")

    season_tag = f"season_{season}_" if season is not None else ""
    source_tag = "_".join(sources)
    filename = f"{season_tag}event_{event_id}_{source_tag}.png"
    out_path = out_dir / filename

    if legacy_map is not None and new_map is not None:
        legacy_map_arr = np.asarray(legacy_map, dtype=float)
        new_map_arr = np.asarray(new_map, dtype=float)
        legacy_vmin, legacy_vmax = _safe_min_max(legacy_map_arr)
        new_vmin, new_vmax = _safe_min_max(new_map_arr)
        legacy_avg = _safe_mean(legacy_map_arr)
        new_avg = _safe_mean(new_map_arr)

        fig, axes = plt.subplots(1, 2, figsize=(11.0, 4.2), constrained_layout=True)
        (ax_l, ax_n) = axes

        _, sm_l = plot_xg_map_cartesian_native(
            legacy_map_arr,
            net_coords=legacy_coords,
            ax=ax_l,
            title=f"Legacy ({legacy_map_arr.shape[0]}×{legacy_map_arr.shape[1]})",
            vmin=legacy_vmin,
            vmax=legacy_vmax,
        )
        _annotate_avg_xg(ax_l, legacy_avg)

        _, sm_n = plot_xg_map_cartesian_native(
            new_map_arr,
            net_coords=new_coords,
            ax=ax_n,
            title=f"New ({new_map_arr.shape[0]}×{new_map_arr.shape[1]})",
            vmin=new_vmin,
            vmax=new_vmax,
        )
        _annotate_avg_xg(ax_n, new_avg)

        fig.colorbar(sm_l, ax=ax_l, shrink=0.88, pad=0.02, aspect=20)
        fig.colorbar(sm_n, ax=ax_n, shrink=0.88, pad=0.02, aspect=20)
        st = f"Season {season} | " if season is not None else ""
        fig.suptitle(f"{st}Event {event_id}", fontsize=11)
        fig.savefig(out_path, dpi=160)
        plt.close(fig)
        return out_path

    # Single-panel fallback for mismatch samples.
    solo_map = legacy_map if legacy_map is not None else new_map
    solo_coords = legacy_coords if legacy_map is not None else new_coords
    solo_label = "Legacy" if legacy_map is not None else "New"

    solo_arr = np.asarray(solo_map, dtype=float)
    vmin, vmax = _safe_min_max(solo_arr)
    avg_xg = _safe_mean(solo_arr)

    fig, ax = plt.subplots(1, 1, figsize=(5.6, 4.2), constrained_layout=True)
    _, sm = plot_xg_map_cartesian_native(
        solo_arr,
        net_coords=solo_coords,
        ax=ax,
        title=f"{solo_label} ({solo_arr.shape[0]}×{solo_arr.shape[1]})",
        vmin=vmin,
        vmax=vmax,
    )
    _annotate_avg_xg(ax, avg_xg)
    fig.colorbar(sm, ax=ax, shrink=0.92, pad=0.02, aspect=20)
    st = f"Season {season} | " if season is not None else ""
    fig.suptitle(f"{st}Event {event_id} | {solo_label}-only", fontsize=11)
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def _clustering_sql_games(seasons: list[int], top_n: int) -> str:
    seasons_str = ",".join(str(int(s)) for s in seasons)
    return f"""
        WITH per_event AS (
            SELECT
                g.SEASON AS season,
                e.GAME_ID_HAWKS AS game_id_hawks,
                e.EVENT_ID_HAWKS AS event_id_hawks
            FROM public.event AS e
            JOIN public.game AS g
              ON g.GAME_ID_HAWKS = e.GAME_ID_HAWKS
            WHERE g.SEASON IN ({seasons_str})
              AND e.EVENT_NAME = 'shot'
        ), flags AS (
            SELECT
                season,
                game_id_hawks,
                event_id_hawks,
                IFF(EXISTS (SELECT 1 FROM {NEW_TABLE}  n WHERE n.EVENT_ID_HAWKS = per_event.event_id_hawks), 1, 0) AS has_new,
                IFF(EXISTS (SELECT 1 FROM {LEGACY_TABLE} l WHERE l.EVENT_ID_HAWKS = per_event.event_id_hawks), 1, 0) AS has_legacy
            FROM per_event
        ), agg AS (
            SELECT
                season,
                game_id_hawks,
                SUM(IFF(has_new = 1 AND has_legacy = 0, 1, 0)) AS new_only_count,
                SUM(IFF(has_new = 0 AND has_legacy = 1, 1, 0)) AS legacy_only_count,
                SUM(IFF(has_new = 1 AND has_legacy = 1, 1, 0)) AS overlap_count,
                COUNT(*) AS shot_event_count
            FROM flags
            GROUP BY season, game_id_hawks
        ), ranked AS (
            SELECT
                *,
                ROW_NUMBER() OVER (PARTITION BY season ORDER BY new_only_count DESC, game_id_hawks) AS rank_new_only,
                ROW_NUMBER() OVER (PARTITION BY season ORDER BY legacy_only_count DESC, game_id_hawks) AS rank_legacy_only
            FROM agg
        )
        SELECT
            season,
            game_id_hawks,
            new_only_count,
            legacy_only_count,
            overlap_count,
            shot_event_count,
            rank_new_only,
            rank_legacy_only
        FROM ranked
        WHERE (rank_new_only <= {int(top_n)} AND new_only_count > 0)
           OR (rank_legacy_only <= {int(top_n)} AND legacy_only_count > 0)
        ORDER BY season ASC, GREATEST(new_only_count, legacy_only_count) DESC, game_id_hawks ASC
        ;
    """


def _clustering_sql_players(seasons: list[int], top_n: int) -> str:
    seasons_str = ",".join(str(int(s)) for s in seasons)
    return f"""
        WITH per_event AS (
            SELECT
                g.SEASON AS season,
                e.PLAYER_ID_HAWKS AS player_id_hawks,
                e.EVENT_ID_HAWKS AS event_id_hawks
            FROM public.event AS e
            JOIN public.game AS g
              ON g.GAME_ID_HAWKS = e.GAME_ID_HAWKS
            WHERE g.SEASON IN ({seasons_str})
              AND e.EVENT_NAME = 'shot'
        ), flags AS (
            SELECT
                season,
                player_id_hawks,
                event_id_hawks,
                IFF(EXISTS (SELECT 1 FROM {NEW_TABLE}  n WHERE n.EVENT_ID_HAWKS = per_event.event_id_hawks), 1, 0) AS has_new,
                IFF(EXISTS (SELECT 1 FROM {LEGACY_TABLE} l WHERE l.EVENT_ID_HAWKS = per_event.event_id_hawks), 1, 0) AS has_legacy
            FROM per_event
        ), agg AS (
            SELECT
                season,
                player_id_hawks,
                SUM(IFF(has_new = 1 AND has_legacy = 0, 1, 0)) AS new_only_count,
                SUM(IFF(has_new = 0 AND has_legacy = 1, 1, 0)) AS legacy_only_count,
                SUM(IFF(has_new = 1 AND has_legacy = 1, 1, 0)) AS overlap_count,
                COUNT(*) AS shot_event_count
            FROM flags
            GROUP BY season, player_id_hawks
        ), ranked AS (
            SELECT
                *,
                ROW_NUMBER() OVER (PARTITION BY season ORDER BY new_only_count DESC, player_id_hawks) AS rank_new_only,
                ROW_NUMBER() OVER (PARTITION BY season ORDER BY legacy_only_count DESC, player_id_hawks) AS rank_legacy_only
            FROM agg
        )
        SELECT
            season,
            player_id_hawks,
            new_only_count,
            legacy_only_count,
            overlap_count,
            shot_event_count,
            rank_new_only,
            rank_legacy_only
        FROM ranked
        WHERE (rank_new_only <= {int(top_n)} AND new_only_count > 0)
           OR (rank_legacy_only <= {int(top_n)} AND legacy_only_count > 0)
        ORDER BY season ASC, GREATEST(new_only_count, legacy_only_count) DESC, player_id_hawks ASC
        ;
    """


def _write_clustering_csvs(*, seasons: list[int], top_n: int, out_dir: Path, stem: str) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)

    game_df = db.get_df(_clustering_sql_games(seasons, top_n)).rename(columns=str.lower)
    player_df = db.get_df(_clustering_sql_players(seasons, top_n)).rename(columns=str.lower)

    out_paths: list[Path] = []

    games_path = out_dir / f"{stem}_cluster_games_top{top_n}.csv"
    game_df.to_csv(games_path, index=False)
    out_paths.append(games_path)

    players_path = out_dir / f"{stem}_cluster_players_top{top_n}.csv"
    player_df.to_csv(players_path, index=False)
    out_paths.append(players_path)

    return out_paths


def main() -> None:
    args = _build_parser().parse_args()

    if args.max_events <= 0:
        raise ValueError("--max-events must be > 0")
    if args.top_n <= 0:
        raise ValueError("--top-n must be > 0")

    use_plot_dir = args.from_plot_dir is not None
    use_filtered_sampling = bool(args.player_ids_file or args.shot_types)

    payload: dict | None = None
    report_path: Path | None = None
    sample_events: list[SampleEvent] = []

    if use_plot_dir:
        print("=" * 80)
        print("Phase 2: xG-map migration sanity checks (replot existing batch)")
        print("=" * 80)
        print(f"Plot dir:      {args.from_plot_dir}")
        print(f"Max events:    {args.max_events}")
        print(f"Plots root:    {args.plots_root}")
        print("=" * 80)

        sample_events = _parse_plot_dir_events(args.from_plot_dir)
        if not sample_events:
            raise RuntimeError(f"No event IDs found in plot dir: {args.from_plot_dir}")
        sample_events = sample_events[: args.max_events]
    elif use_filtered_sampling:
        seasons = args.seasons if args.seasons else [20232024, 20242025]
        player_ids = _load_player_ids(args.player_ids_file) if args.player_ids_file else None
        shot_types = list(args.shot_types) if args.shot_types else None

        print("=" * 80)
        print("Phase 2: xG-map migration sanity checks (filtered sampling)")
        print("=" * 80)
        print(f"Seasons:        {seasons}")
        print(f"Player IDs:     {len(player_ids) if player_ids else 0} (from {args.player_ids_file})")
        print(f"Shot types:     {shot_types}")
        print(f"Max events:     {args.max_events}")
        print(f"Seed:           {args.seed}")
        print(f"Plots root:     {args.plots_root}")
        print("=" * 80)

        sample_events = _sample_overlap_events_filtered(
            seasons=seasons,
            player_ids=player_ids,
            shot_types=shot_types,
            max_events=args.max_events,
            seed=args.seed,
        )

        if not sample_events:
            raise RuntimeError(
                "No overlap events found for the requested filters (player IDs / shot types / seasons)."
            )
    else:
        report_path = args.report_json
        if report_path is None:
            report_path = _find_latest_report(DEFAULT_REPORT_DIR)

        payload = _load_phase1_report(report_path)
        sample_events = _iter_sample_events(payload)
        sample_events = sample_events[: args.max_events]

    started_at = datetime.now()
    timestamp = started_at.strftime("%Y%m%d_%H%M%S")
    stem = f"xg_map_migration_phase2_{timestamp}"

    if not use_filtered_sampling and not use_plot_dir:
        print("=" * 80)
        print("Phase 2: xG-map migration sanity checks")
        print("=" * 80)
        print(f"Phase 1 report: {report_path}")
        print(f"Max events:     {args.max_events}")
        print(f"Plots root:     {args.plots_root}")
        print(f"Out report dir: {args.out_report_dir}")
        print(f"Top-N:         {args.top_n}")
        print("NOTE: Clustering groups by numeric IDs (GAME_ID_HAWKS / PLAYER_ID_HAWKS);")
        print("      if GAME_DATE/PLAYER_NAME columns are needed, add them once schemas are confirmed.")
        print("=" * 80)

    cluster_seasons: list[int] = []
    if payload is not None:
        seasons_in_report = payload.get("seasons") or []
        seasons: list[int] = []
        for s in seasons_in_report:
            try:
                seasons.append(int(s))
            except Exception:  # noqa: BLE001
                continue
        seasons = sorted(set(seasons))

        # Prefer overlap-era seasons by default (acceptance focuses on 20212022–20242025).
        cluster_seasons = [s for s in seasons if 20212022 <= int(s) <= 20242025]
        if not cluster_seasons:
            cluster_seasons = seasons

    if not sample_events:
        print("No sampled event_ids found in report; nothing to plot")
        return

    event_ids = [s.event_id for s in sample_events]

    if not args.skip_plots:
        # Fetch in batch to avoid N round-trips.
        legacy_maps = queries.get_shot_maps_by_event_ids(event_ids)
        new_maps = queries.get_shot_maps_by_event_ids_new_xg(event_ids)

        out_dir = args.plots_root / timestamp
        out_dir.mkdir(parents=True, exist_ok=True)

        saved: list[Path] = []
        for s in sample_events:
            legacy = legacy_maps.get(s.event_id)
            new = new_maps.get(s.event_id)

            # If the report says overlap but fetch doesn’t return both, still plot what we have.
            if legacy is None and new is None:
                print(f"Event {s.event_id}: no maps returned from either source; skipping")
                continue

            try:
                path = _plot_event(
                    event_id=s.event_id,
                    season=s.season,
                    legacy=legacy,
                    new=new,
                    out_dir=out_dir,
                )
                saved.append(path)
            except Exception as exc:  # noqa: BLE001
                print(f"Event {s.event_id}: failed to plot: {exc!r}")

        print("\nWrote plots:")
        print(f"- {out_dir} ({len(saved)} files)")

    if args.skip_clustering:
        return

    if cluster_seasons:
        out_paths = _write_clustering_csvs(
            seasons=cluster_seasons,
            top_n=args.top_n,
            out_dir=args.out_report_dir,
            stem=stem,
        )
        print("\nWrote clustering CSVs:")
        for p in out_paths:
            print(f"- {p}")
    else:
        print("Skipping clustering: no seasons found in report JSON")


if __name__ == "__main__":
    main()
