"""Batch visualization script for hockey angular heatmaps across all players.

This module serves as a convenience wrapper around ``makePlotsAngularHeatmaps.py``
to automate the generation of angular heatmap visualizations for all players and
shot types in a given experiment. Instead of manually specifying each player and
shot type combination, this script reads the experiment's ``statsAfterFiltering.json``
file and processes all recorded player-shot combinations in sequence.

The script is particularly useful when analyzing multi-player experiments or when
a large number of shot attempts need to be visualized across different players and
shot types (e.g., wristshot, snapshot, slapshot).

Workflow
--------
1. Load the experiment folder specified via command line
2. Read ``statsAfterFiltering.json`` to identify all player-shot combinations
3. For each combination, invoke ``makePlots()`` from ``makePlotsAngularHeatmaps``
4. Generate complete heatmap visualizations for each player and shot type

Command-Line Usage
------------------
When run as a script, expects one argument:
    1. experimentFolder: Name of the experiment folder under 'Experiments/hockey-multi/'

Example:
    python makePlotsAngularHeatmapsAllPlayers.py my_experiment

Input Requirements
------------------
Requires:
1. ``statsAfterFiltering.json`` in Data/JSON/ (created by getStatsJson.py)
2. Angular heatmap data files in Data/AngularHeatmaps/ (created by getAngularHeatmapsPerPlayer.py)

Output
------
Generates the same output structure as ``makePlotsAngularHeatmaps.py`` for each
player and shot type combination:
    Experiments/hockey-multi/{experimentFolder}/Data/Plots/Heatmaps/Player{playerID}/{typeShot}/
    - Comparison heatmaps (YZ vs angular)
    - Rink diagrams in the Rink/ subdirectory

Notes
-----
This is a batch processing script with minimal logic - it delegates all plotting
work to the ``makePlots()`` function. Progress messages are printed to stdout to
track which player-shot combinations are being processed.
"""

from makePlotsAngularHeatmaps import makePlots
import json
import sys
import os


# ---------------------------------------------------------------------------
#  Main entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    # Parse command-line argument for the experiment folder
    try:
        experimentFolder = sys.argv[1]
    except Exception:
        print(
            "Need to specify the name of the folder for the experiment (located under\n"
            "'Experiments/hockey-multi/') as command line argument."
        )
        sys.exit(1)

    # Build path to the experiment's main directory
    mainFolder = f"Experiments{os.sep}hockey-multi{os.sep}{experimentFolder}{os.sep}"

    # Load the statsAfterFiltering.json file which contains all player-shot combinations
    # This file is generated by getStatsJson.py and lists which combinations have sufficient data
    try:
        with open(f"{mainFolder}Data{os.sep}JSON{os.sep}statsAfterFiltering.json", "r") as infile:
            info = json.load(infile)
    except Exception as exc:
        print(exc, "Need to create statsAfterFiltering.json file. Run getStatsJson.py script first.")
        sys.exit(1)

    # Process each player-shot combination in the file
    # Each entry is a list: [playerID, typeShot]
    for each in info:
        playerID = each[0]
        typeShot = each[1]

        # Print progress message to track which combination is being processed
        print(f"Creating plots for Player {playerID} | Shot Type: {typeShot}")

        # Delegate to makePlotsAngularHeatmaps.makePlots() for the actual visualization
        makePlots(experimentFolder, playerID, typeShot)

